/**
 * Client-side PDF export for the MOC AI Recommendation report — company
 * logo + generated date + provider label, process data, and the AI's
 * summary/sealing/alternatives narrative rendered from markdown (headers,
 * bold, bullets, and pipe tables). Pure client-side (jsPDF + jspdf-autotable,
 * no server round-trip) so it can run from a "use client" step component.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { MocComponentSuggestions } from "../services/mocRecommendationService";

export interface MocPdfInput {
  media: string;
  head?: string;
  headUnit?: string;
  ph?: string;
  temperatureC?: string;
  viscosityCp?: string;
  sg?: string;
  capacity?: string;
  capacityUnit?: string;
  solidPct?: string;
  solidSize?: string;
  solidType?: string;
  /** Legacy free-text client extras (older drafts). */
  clientRequirements?: string;
  /** Client-requirements file name (image or PDF) uploaded on the MOC step.
   * The bytes themselves are attached to the AI request directly and not
   * embedded in this PDF - the report just records that a file was used. */
  clientRequirementsFilename?: string;
  suggestion: MocComponentSuggestions;
  /** Logged-in user's display name (or email as a fallback) — shown in the
   * report header as "Generated by X". Not the AI model/provider name. */
  generatedBy?: string;
}

async function loadImageAsDataUrl(url: string): Promise<{ dataUrl: string; width: number; height: number } | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    const dataUrl = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    const dims = await new Promise<{ width: number; height: number }>((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
      img.onerror = () => resolve({ width: 1, height: 1 });
      img.src = dataUrl;
    });
    return { dataUrl, ...dims };
  } catch {
    return null;
  }
}

const POS_GREEN: [number, number, number] = [5, 150, 105];

// jsPDF's built-in Helvetica is a Latin-1 (WinAnsi) font — codepoints above
// 0xFF render as garbage (e.g. an emoji shows up as multiple corrupt bytes
// like "'L" instead of the intended symbol). The prompt tells the model to
// stay ASCII, but real-world responses still slip in the occasional em-dash,
// smart quote, arrow, or check-mark. Sanitize defensively so the PDF stays
// legible regardless.
const UNICODE_REPLACEMENTS: [RegExp, string][] = [
  // Emoji / status symbols the AI might use as bullet markers
  [/[✅✓✔]/g, "OK "], // ✅ ✓ ✔
  [/[❌✖✘]/g, "X "],  // ❌ ✖ ✘
  [/[⚠❗‼️]/g, "! "], // ⚠ ❗ ‼ (+ VS16 selector)
  [/[⭐★☆]/g, "* "], // ⭐ ★ ☆
  // Punctuation / math
  [/[–—−]/g, "-"],   // – — −
  [/[‘’‚‹›]/g, "'"], // ‘ ’ ‚ ‹ ›
  [/[“”„]/g, '"'],   // “ ” „
  [/[…]/g, "..."],             // …
  [/[•●○▪◦]/g, "-"], // • ● ○ ▪ ◦
  [/[≈]/g, "~"],               // ≈
  [/[→➡]/g, "->"],        // → ➡
  [/[←]/g, "<-"],              // ←
  [/[×]/g, "x"],               // ×
  [/[≤]/g, "<="],              // ≤
  [/[≥]/g, ">="],              // ≥
  [/[±]/g, "+/-"],             // ±
  // Non-breaking + narrow spaces → normal space
  [/[   ]/g, " "],
];

function sanitizeForPdf(text: string): string {
  if (!text) return text;
  let out = text;
  for (const [pattern, replacement] of UNICODE_REPLACEMENTS) {
    out = out.replace(pattern, replacement);
  }
  // Strip any lingering non-Latin-1 codepoints (emoji, CJK, etc.) that we
  // don't have a specific replacement for — they'd render as garbage anyway.
  out = out.replace(/[^\x00-\xFF]/g, "");
  // Collapse repeated whitespace that the substitutions above may have
  // introduced (e.g. "!! " from a doubled warning-triangle).
  out = out.replace(/[ \t]{2,}/g, " ");
  return out;
}

// The AI is prompted to write summary/alternatives as markdown (headers,
// **bold**, bullets, and pipe tables) so the PDF reads like the same
// formatted answer you'd see prompting the model directly in a chat UI,
// rather than one flat wrapped paragraph. This is a small, purpose-built
// renderer (not a full markdown parser) covering just what the prompt asks
// the model for: #/## headers, "- "/"* "/"1. " list items, **bold** inline
// spans, and GitHub-style | pipe | tables (rendered via jspdf-autotable).
type MdToken = { text: string; bold: boolean };

function parseInlineBold(text: string): MdToken[] {
  const tokens: MdToken[] = [];
  const re = /\*\*(.+?)\*\*/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) tokens.push({ text: text.slice(last, m.index), bold: false });
    tokens.push({ text: m[1], bold: true });
    last = re.lastIndex;
  }
  if (last < text.length) tokens.push({ text: text.slice(last), bold: false });
  return tokens;
}

const isTableRow = (s: string) => /^\|.*\|$/.test(s.trim());
// A table separator row like "| --- | :--: |" — pipes/dashes/colons/spaces
// only, and must contain at least one dash so it isn't mistaken for a body
// row of short cells.
const isTableSep = (s: string) =>
  /^\|[\s:|-]+\|$/.test(s.trim()) && s.includes("-");

function splitTableRow(line: string): string[] {
  return line
    .trim()
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    // Tables render as flat cells; strip inline bold markers so "**x**"
    // doesn't show literal asterisks (autoTable can't do partial-bold spans).
    .map((c) => sanitizeForPdf(c.trim().replace(/\*\*(.+?)\*\*/g, "$1")));
}

const GREY_HEAD: [number, number, number] = [55, 65, 81];

// Look ahead for the smallest "keep together" block starting at a heading —
// the heading itself plus its first non-blank following line. If that block
// won't fit on the current page, force a page break BEFORE the heading so
// it never orphans at the bottom.
function headingBlockHeight(lines: string[], headingIdx: number): number {
  let followingLines = 0;
  for (let k = headingIdx + 1; k < lines.length && followingLines < 2; k++) {
    if (lines[k].trim() !== "") followingLines++;
  }
  // heading line = 16px + up to 2 body/heading-adjacent lines at 13px each
  return 16 + followingLines * 13;
}

// Self-contained: manages its own page breaks (returns the final y) so callers
// just assign the result back — no shared ensureSpace closure to keep in sync.
function renderMarkdown(
  doc: jsPDF,
  text: string,
  margin: number,
  contentWidth: number,
  pageHeight: number,
  startY: number,
): number {
  let y = startY;
  const bottom = pageHeight - margin - 20;
  const need = (h: number) => {
    if (y + h > bottom) {
      doc.addPage();
      y = margin;
    }
  };

  const lines = (text || "").split("\n");
  let i = 0;
  while (i < lines.length) {
    const raw = lines[i];
    const trimmed = raw.trim();

    // --- Pipe table (header row + separator row + body rows) ---
    if (isTableRow(trimmed) && i + 1 < lines.length && isTableSep(lines[i + 1])) {
      const header = splitTableRow(trimmed);
      const body: string[][] = [];
      let j = i + 2;
      while (j < lines.length && isTableRow(lines[j]) && !isTableSep(lines[j])) {
        body.push(splitTableRow(lines[j]));
        j++;
      }
      need(40);
      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [header],
        body,
        styles: { fontSize: 8.5, cellPadding: 4, textColor: 40, valign: "top" },
        headStyles: { fillColor: GREY_HEAD, textColor: 255, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 247, 250] },
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      y = (doc as any).lastAutoTable.finalY + 10;
      i = j;
      continue;
    }

    if (!trimmed) {
      y += 6;
      i++;
      continue;
    }

    let content = trimmed;
    let isHeading = false;
    let prefix = "";
    let indent = 0;

    const heading = /^#{1,4}\s+(.*)$/.exec(trimmed);
    const bullet = /^[-*]\s+(.*)$/.exec(trimmed);
    const numbered = /^(\d+[.)])\s+(.*)$/.exec(trimmed);
    if (heading) {
      isHeading = true;
      content = heading[1];
      // Never let a heading orphan at the very bottom of a page — force a
      // break early if the heading + its first following lines won't fit.
      need(headingBlockHeight(lines, i));
    } else if (bullet) {
      prefix = "- ";
      indent = 14;
      content = bullet[1];
    } else if (numbered) {
      prefix = `${numbered[1]} `;
      indent = 14;
      content = numbered[2];
    }

    // Sanitize AFTER markdown parsing so the parser's regexes see the raw
    // characters (e.g. asterisks) but the rendered glyphs are all Latin-1.
    content = sanitizeForPdf(content);

    need(14);
    doc.setFontSize(isHeading ? 11 : 10);
    let x = margin + indent;
    if (prefix) {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50);
      doc.text(prefix, x, y);
      x += doc.getTextWidth(prefix);
    }

    for (const tok of parseInlineBold(content)) {
      doc.setFont("helvetica", tok.bold || isHeading ? "bold" : "normal");
      doc.setTextColor(isHeading ? 20 : 50);
      for (const word of tok.text.split(/(\s+)/)) {
        if (!word) continue;
        const w = doc.getTextWidth(word);
        if (word.trim() && x + w > margin + contentWidth) {
          y += 13;
          need(14);
          x = margin + indent;
        }
        doc.text(word, x, y);
        x += w;
      }
    }
    y += isHeading ? 16 : 13;
    i++;
  }
  return y + 6;
}

export interface MocPdfResult {
  filename: string;
  /** Raw PDF bytes — lets the caller also upload the same document to the
   * server (see moc_sealing_input.document) without regenerating it. */
  bytes: ArrayBuffer;
}

export async function downloadMocReportPdf(input: MocPdfInput): Promise<MocPdfResult> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  let y = 40;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin - 20) {
      doc.addPage();
      y = margin;
    }
  };

  // --- Header: logo, generated date, provider ---
  const logo = await loadImageAsDataUrl("/logo.png");
  if (logo) {
    const targetH = 36;
    const targetW = (logo.width / logo.height) * targetH;
    doc.addImage(logo.dataUrl, margin, y, targetW, targetH);
  }
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.setFont("helvetica", "normal");
  const dateStr = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
  // Right column: date on top, provider label right below it — both anchored
  // to the same right margin so they stack cleanly.
  doc.text(`Generated: ${dateStr}`, pageWidth - margin, y + 14, { align: "right" });
  if (input.generatedBy) {
    doc.text(`Generated by ${sanitizeForPdf(input.generatedBy)}`, pageWidth - margin, y + 28, {
      align: "right",
    });
  }
  y += 55;

  doc.setFontSize(17);
  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.text("MOC & Sealing Recommendation Report", margin, y);
  y += 6;
  doc.setDrawColor(210);
  doc.line(margin, y, pageWidth - margin, y);
  y += 18;

  // --- Process data ---
  const allProcRows: [string, string][] = [
    ["Media / Application", input.media],
    ["Head", input.head ? `${input.head} ${input.headUnit || "MWC"}` : ""],
    ["pH", input.ph ?? ""],
    ["Temperature", input.temperatureC ? `${input.temperatureC} °C` : ""],
    ["Viscosity", input.viscosityCp ? `${input.viscosityCp} cP` : ""],
    ["Specific Gravity", input.sg ?? ""],
    [
      "Flow Rate",
      input.capacity ? `${input.capacity} ${input.capacityUnit ?? ""}`.trim() : "",
    ],
    ["Solids", input.solidPct ? `${input.solidPct}%` : ""],
    [
      "Particle Size",
      input.solidSize
        ? `${input.solidSize} mm${input.solidType ? ` (${input.solidType})` : ""}`
        : "",
    ],
  ];
  // Client requirements go last - free-form and usually multi-line, so they
  // read better after the fixed process values than interleaved with them.
  // New rows use the file name; legacy rows may still carry text.
  if (input.clientRequirementsFilename && input.clientRequirementsFilename.trim() !== "") {
    allProcRows.push([
      "Client Requirements File",
      input.clientRequirementsFilename.trim(),
    ]);
  }
  if (input.clientRequirements && input.clientRequirements.trim() !== "") {
    allProcRows.push(["Client Requirements", input.clientRequirements.trim()]);
  }
  const procRows = allProcRows
    .filter(([, v]) => v !== "")
    .map(([k, v]) => [sanitizeForPdf(k), sanitizeForPdf(v)]);

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    body: procRows,
    theme: "plain",
    styles: { fontSize: 9, cellPadding: 2, textColor: 40 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 140 } },
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 20;

  // --- Summary / Sealing / Alternatives — rendered as markdown so the PDF
  // reads like the same formatted answer the model gives in a chat UI. ---
  const contentWidth = pageWidth - margin * 2;
  // Section titles keep their own header text with the first ~2 lines of
  // content — never orphan a title on the last line of a page.
  const sectionTitle = (title: string, minFollowingHeight = 40) => {
    ensureSpace(20 + minFollowingHeight);
    doc.setFontSize(12);
    doc.setTextColor(20);
    doc.setFont("helvetica", "bold");
    doc.text(sanitizeForPdf(title), margin, y);
    y += 15;
  };

  sectionTitle("Summary");
  y = renderMarkdown(doc, input.suggestion.summary || "-", margin, contentWidth, pageHeight, y);
  y += 4;

  sectionTitle("Recommended Sealing", 50);
  ensureSpace(20);
  doc.setFontSize(10.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...POS_GREEN);
  doc.text(sanitizeForPdf(input.suggestion.sealRecommendation || "-"), margin, y);
  y += 14;
  if (input.suggestion.sealMoc && input.suggestion.sealMoc.trim() !== "") {
    ensureSpace(16);
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40);
    y = renderMarkdown(
      doc,
      `**Seal MOC:** ${input.suggestion.sealMoc}`,
      margin,
      contentWidth,
      pageHeight,
      y,
    );
    y += 2;
  }
  y = renderMarkdown(doc, input.suggestion.sealRationale || "", margin, contentWidth, pageHeight, y);
  y += 4;

  sectionTitle("Alternatives Considered", 60);
  y = renderMarkdown(doc, input.suggestion.alternatives || "-", margin, contentWidth, pageHeight, y);

  // --- Footer on every page ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.setFont("helvetica", "normal");
    doc.text(
      "AI-generated estimate, not a verified specification - review before use.",
      margin,
      pageHeight - 18,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 18, {
      align: "right",
    });
  }

  const safeMedia = input.media.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "");
  const dateSlug = new Date().toISOString().slice(0, 10);
  const filename = `MOC-Report-${safeMedia || "media"}-${dateSlug}.pdf`;
  doc.save(filename);

  return { filename, bytes: doc.output("arraybuffer") };
}
