/**
 * AI-assisted, per-component MOC/elastomer/sealing suggestion for the MOC &
 * Elastomer wizard step. Advisory only, clearly badged as an AI suggestion in
 * the UI, never a substitute for the manual selectors — and never throws: an
 * unset API key, a blocked response, or any request failure just returns
 * null and the caller falls back to "unavailable".
 *
 * Provider: Claude Haiku 4.5 via @anthropic-ai/sdk. Requires ANTHROPIC_API_KEY.
 * Structured output via a forced tool call — the SDK hands back already-parsed
 * JSON in the tool_use block's `input`, no manual JSON.parse needed. (A Google
 * Gemini provider used to be selectable here too; it was removed.)
 *
 * Component breakdown is per the user's spec sheet: non-wettable components
 * (Bearing Housing, Base Plate or Mounting Plate, Tie Rod, Nut & Bolt) and
 * wettable-casting components (Pump Housing, Rotor, Shaft), plus the stator
 * rubber elastomer. The Stator Sleeve joins the non-wettable group on a
 * Horizontal pump and the wettable group on a Vertical one, and the plate is a
 * base plate on Horizontal / a mounting plate on Vertical - both are resolved
 * per request (see schemaPropertiesFor / buildPrompt).
 * MOC_AI_MATERIALS / MOC_AI_ELASTOMERS below are the options offered in the
 * UI's *manual* dropdowns — they are NOT a hard constraint on the AI's own
 * answer. The AI is free to recommend something outside those lists (e.g. an
 * exotic alloy) when the media genuinely calls for it; it's told to say so
 * explicitly rather than being forced into the closest list entry.
 */

export const MOC_AI_MATERIALS = [
  "Cast Iron",
  "Mild Steel",
  "SS410",
  "SS304",
  "SS316",
  "SS316L",
  "SDSS 2507",
  "DSS 2505",
  "Hastelloy",
  "Ni-Hard CI",
] as const;

export const MOC_AI_ELASTOMERS = [
  "Nitrile",
  "FG Nitrile",
  "White Nitrile",
  "Natural",
  "Hypalon",
  "EPDM",
  "Viton",
] as const;

export const MOC_AI_SEAL_TYPES = ["Gland Packing", "Mechanical Seal"] as const;

/** LLM provider(s) for the MOC AI recommendation. Only Anthropic (Claude
 * Haiku 4.5) remains — kept as a one-element list so the provider plumbing
 * (persisted mocAiProvider, the "Generated by" label) still works and a
 * second provider can be re-added without reshaping everything. */
export const MOC_AI_PROVIDERS = ["anthropic"] as const;
export type MocAiProvider = (typeof MOC_AI_PROVIDERS)[number];

export interface MocAiContext {
  media: string;
  /** Operating-Conditions pump type. Decides whether the stator sleeve is a
   * wetted part (Vertical) or a dry structural one (the Horizontal
   * variants), which changes the material it needs. */
  pumpType: string | null;
  head: string | null;
  headUnit: string | null;
  capacity: string | null;
  capacityUnit: string | null;
  ph: string | null;
  temperatureC: string | null;
  viscosityCp: string | null;
  sg: string | null;
  solidPct: string | null;
  solidSize: string | null;
  solidType: string | null;
  /** Legacy free-text extras (kept for old drafts saved before the field
   * became a file upload). Appended to the prompt when present. */
  clientRequirements: string | null;
  /** Client-supplied requirements document (image or PDF) attached to the
   * request as an image or document content block. mediaType is the MIME
   * string the DB has stored, base64 is the raw file bytes. */
  clientRequirementsFile: { mediaType: string; base64: string } | null;
}

export interface MocComponentSuggestions {
  // Non-wettable components
  bearingHousing: string;
  /** Horizontal pump types only - a Vertical pump has a mounting plate
   *  instead, which is a different component (see mountingPlate). */
  basePlate: string;
  /** Vertical pump types only. */
  mountingPlate: string;
  tieRod: string;
  nutBolt: string;
  // Wettable casting components
  pumpHousing: string;
  rotor: string;
  shaft: string;
  // Elastomer
  statorRubber: string;
  // Stator sleeve (wetted on Vertical pumps, structural on Horizontal)
  statorSleeve: string;
  // Sealing
  sealRecommendation: string;
  /** MOC of the recommended seal itself — for a Mechanical Seal: body/metal
   * grade, face pair and O-ring elastomer; for Gland Packing: the packing
   * material. */
  sealMoc: string;
  sealRationale: string;
  // Report content (rendered in the UI's Summary panel and exported to PDF)
  summary: string;
  alternatives: string;
}

// Fields the tool must always return. The plates are handled separately —
// only ONE exists per pump type (Base on Horizontal, Mounting on Vertical),
// so only that one is asked for (see requiredFieldsFor / schemaPropertiesFor).
const BASE_REQUIRED_FIELDS: (keyof MocComponentSuggestions)[] = [
  "bearingHousing", "tieRod", "nutBolt",
  "pumpHousing", "rotor", "shaft", "statorRubber", "statorSleeve",
  "sealRecommendation", "sealMoc", "sealRationale", "summary", "alternatives",
];

/** The plate that actually exists on this pump type — the only one the model
 * is asked for, so there's no phantom "not present" field to work around. */
function activePlateField(pumpType: string | null): "mountingPlate" | "basePlate" {
  return pumpType === "Vertical" ? "mountingPlate" : "basePlate";
}

function requiredFieldsFor(pumpType: string | null): (keyof MocComponentSuggestions)[] {
  return [...BASE_REQUIRED_FIELDS, activePlateField(pumpType)];
}

// JSON-Schema property map driving Anthropic's tool input_schema (structured
// output).
// Wetted status is THE main driver of material choice, so it is stated on
// every component rather than left for the model to infer from the name: a
// wetted part is picked for resistance to the media, a dry one for strength
// and cost. These strings mirror the two groups the MOC step renders on
// screen (see componentGroupsFor in MocDetailsStep.tsx), so the AI answer and
// the UI grouping agree.
const WETTED =
  "WETTED - in direct contact with the pumped media. Material must resist the media (corrosion/abrasion) at the stated pH, temperature and solids.";
const DRY =
  "NON-WETTED structural part - no media contact. Choose for strength and cost; media resistance does not apply, so do not over-specify an expensive alloy here.";

// Component groups per pump type × wetted status. The prompt's wettable /
// non-wettable listing is built from these arrays instead of hardcoded
// sentences, keeping the prompt small and the two pump-type layouts in sync.
// Two components differ by pump type: the plate (Base on Horizontal, Mounting
// on Vertical) and the Stator Sleeve (dry on Horizontal, wetted on Vertical).
const HORIZONTAL_WETTABLE_COMP = ["Pump Housing", "Rotor", "Shaft"];
const HORIZONTAL_NONWETTABLE_COMP = [
  "Bearing Housing",
  "Base Plate",
  "Tie Rod",
  "Nut & Bolt",
  "Stator Sleeve",
];
// A VERTICAL pump hangs in the liquid, so its tie rods and fasteners sit in
// the media too - they take the SHAFT's MOC, not a structural one. Only the
// bearing housing and the mounting plate stay genuinely dry (per the house
// MOC rules; see STRUCTURAL_MOC_RULES below).
const VERTICAL_WETTABLE_COMP = [
  "Pump Housing",
  "Rotor",
  "Shaft",
  "Stator Sleeve",
  "Tie Rod",
  "Nut & Bolt",
];
const VERTICAL_NONWETTABLE_COMP = ["Bearing Housing", "Mounting Plate"];

// House PREFERENCE for the structural / fastener components — stated in the
// prompt (see STRUCTURAL_MOC_PREFERENCE below) rather than forced onto the
// answer. It is what these parts normally are, not a constraint: the model may
// still deviate when the media genuinely calls for it (an aggressive acid that
// would eat Mild Steel tie rods, say), and is told to say so when it does.
//
//   HORIZONTAL - Stator Sleeve, Tie Rod, Base Plate and Nut & Bolt are dry
//                structural parts -> normally Mild Steel.
//   VERTICAL   - the pump hangs in the liquid, so Stator Sleeve, Tie Rod and
//                Nut & Bolt are wetted and normally take the SHAFT's MOC;
//                only the Mounting Plate stays dry -> normally Mild Steel.
//
// Bearing Housing is deliberately not covered — always the model's call.
const STRUCTURAL_MOC_PREFERENCE =
  "Structural / fastener preference (house practice - follow it unless the media genuinely rules it out, and say why if you deviate): " +
  "HORIZONTAL - Stator Sleeve, Tie Rod, Base Plate and Nut & Bolt are dry structural parts, normally Mild Steel but can be other materials if necessary. " +
  "VERTICAL - the pump hangs in the liquid, so Stator Sleeve, Tie Rod and Nut & Bolt are wetted and normally take the SAME MOC as the Shaft; only the Mounting Plate is dry, normally Mild Steel but can be other materials if necessary. "
// Cost-optimized MOC engineering precedents (distilled from real single-screw /
// PCP enquiry recommendations) — fed to the model as strong guidance so its
// picks follow the same "don't over-specify" logic: match on media CHEMISTRY,
// not the liquid's name; prefer the economical build and step up only when the
// chemistry / temperature / solids justify it, with a stated reason. Kept
// compact on purpose. Update this block when new precedents are added.
const MOC_REFERENCE =
  "It is just an guidance example, no need to follow it blindly. You should recommend the best low cost MOC for the given media and its conditions.\n" +
  STRUCTURAL_MOC_PREFERENCE +
  "Examples (media -> Pump Housing / Rotor / Shaft / Stator Rubber / Seal):\n" +
  "Oil+water 15:85, 70C, 5-20cP: Cast Iron / SS420 hardened / SS410 / Nitrile / Single Mechanical Seal (Carbon-SiC, NBR) [SS316 if produced/sea water or high chloride].\n" +
  "Sewage / STP: Cast Iron / alloy steel hard-chrome / SS410 / Nitrile / Gland Packing.\n" +
  "Starch slurry, 80-95C, 100-5000cP: SS304 / SS410 hard-chrome / SS304 / EPDM / Single Mechanical Seal (Carbon-Ceramic) [SS316 if chlorides].\n" +
  "Dairy cream + hot CIP (95C caustic/nitric): SS316L (product-contact) / SS410 / SS316L / food-grade HNBR / Single Mechanical Seal (SiC-Carbon).\n" +
  "CPI feed pump (non-corrosive): Cast Iron / SS304 / SS304 / Nitrile / Single Mechanical Seal (Carbon-Ceramic, SS304, NBR).\n" +
  "Sodium sulfate + NaCl solution, 60C, 35-40% solids: SS316L / SS316L hard-chrome (or 17-4PH) / SS316L / EPDM / Single Mechanical Seal with external flush [Duplex 2205 if chloride high; avoid Super Duplex unless corrosion calc justifies].\n" +
  "Molasses / sugar A-wash, 65C, Brix~85: Cast Iron / SS420 hardened hard-chrome / SS410 / Nitrile / Single Mechanical Seal (Carbon-SiC) or PTFE-graphite Gland Packing.\n" +
  "Calcium carbonate slurry, pH7-8: Cast Iron / SS420 hard-chrome / SS410 / Nitrile (Natural Rubber for max abrasion) / Gland Packing (aramid/PTFE) or Single Mechanical Seal SiC-SiC.\n" +
  "Neutral scrubber slurry, pH7, 60C, fine abrasive: SS304 / SS304 / SS304 / Natural Rubber / Single Mechanical Seal (Carbon-SiC, EPDM).\n" +
  "Ceramic slurry, 60C, ~50cP, abrasive, high pressure: Cast Iron / SS410 hardened / alloy steel / Nitrile (abrasion grade; EPDM if alkaline) / Single Mechanical Seal SiC-SiC (NBR/EPDM, SS316).\n"+
  "Recommend Cast Iron for Pump Housing only if it is reliable and suitable for the media"

// JSON-Schema property map driving Anthropic's tool input_schema (structured
// output). Built per request because two components change meaning with the
// pump type: the stator sleeve is wetted only on a Vertical pump, and the
// base plate (Horizontal) / mounting plate (Vertical) are different parts of
// which only one actually exists on a given pump.
function schemaPropertiesFor(pumpType: string | null) {
  const vertical = pumpType === "Vertical";
  // Only the plate that exists on this pump type is included — no phantom
  // field, so no "not present, repeat the other value" workaround is needed.
  const plateField = activePlateField(pumpType);
  return {
    bearingHousing: { type: "string", description: DRY },
    [plateField]: { type: "string", description: DRY },
    tieRod: { type: "string", description: DRY },
    nutBolt: { type: "string", description: DRY },
    pumpHousing: { type: "string", description: WETTED },
    rotor: { type: "string", description: WETTED },
    shaft: { type: "string", description: WETTED },
    statorRubber: {
      type: "string",
      // Its own group in the UI with its own option list - a metal answer
      // here cannot be shown in the elastomer dropdown at all.
      description:
        "Stator elastomer. " + WETTED +
        " Answer an elastomer, not a metal. Preferred (not mandatory): " +
        MOC_AI_ELASTOMERS.join(", ") +
        " - another elastomer is fine when the media calls for it; say so explicitly.",
    },
    statorSleeve: {
      type: "string",
      description: vertical
        ? "On this VERTICAL pump the stator sleeve is " + WETTED
        : "On this HORIZONTAL pump the stator sleeve is " + DRY,
    },
    sealRecommendation: { type: "string", enum: [...MOC_AI_SEAL_TYPES] },
    sealMoc: {
      type: "string",
      description:
        "Material of construction of the recommended seal, matched to the media chemistry/abrasion. " +
        "For a Mechanical Seal: state the build - metal/body grade (e.g. SS316), face pair (e.g. SiC/SiC or Carbon/SiC) and O-ring elastomer. " +
        "For Gland Packing: the packing material type(eg - GAGP or Teflon or PTFE or Carbon Fiber or Asbestos-Free or any other you recommend).",
    },
    sealRationale: { type: "string" },
    summary: {
      type: "string",
      description:
        "Concise markdown: Key Design Drivers bullets + ONE Component/Material/Why | pipe table |. " +
        "Do NOT include an operating-parameters table, a seal comparison table, or an alternatives table - those are separate report sections.",
    },
    alternatives: {
      type: "string",
      description:
        "Markdown with ONE | pipe table | of alternative materials and trade-offs. Do not restate the primary selection or the summary.",
    },
  };
}

// Kept short on purpose (token cost) — media/head/capacity are the 3
// parameters that most determine the answer, so they're stated directly in
// the instruction sentence; everything else goes in the compact "Other data"
// block below, only when actually provided.
function buildPrompt(context: MocAiContext, processData: string): string {
  const head = context.head ? `${context.head} ${context.headUnit || "MWC"}` : "n/a";
  const capacity = context.capacity
    ? `${context.capacity} ${context.capacityUnit ?? ""}`.trim()
    : "n/a";
  // Enumerate which of the ancillary parameters the user did NOT enter, so
  // the model knows to assume a typical value for the media and flag it
  // (estimated). Kept to a one-line note in the summary — the input values
  // themselves are already printed in the report's process-data table, so the
  // summary must NOT reprint a full parameters table.
  const missing: string[] = [];
  if (!context.ph) missing.push("pH");
  if (!context.temperatureC) missing.push("Temperature");
  if (!context.viscosityCp) missing.push("Viscosity");
  const missingClause =
    missing.length > 0
      ? `Not provided: ${missing.join(", ")}. In the summary, note the typical value you assumed for each, labeled (estimated), in one line - do not reprint the other parameters. `
      : "";
  const pumpType = context.pumpType ? context.pumpType : "not specified";
  const vertical = context.pumpType === "Vertical";
  // Wetted status drives material choice, and two components change status with
  // the pump type — so state the groups explicitly, built from the component
  // arrays above (compact, and in sync with the on-screen grouping). Stator
  // Rubber is its own elastomer group: it's wetted, but a metal answer is
  // useless to the UI's rubber dropdown, so it's called out separately.
  const wettable = vertical ? VERTICAL_WETTABLE_COMP : HORIZONTAL_WETTABLE_COMP;
  const nonWettable = vertical ? VERTICAL_NONWETTABLE_COMP : HORIZONTAL_NONWETTABLE_COMP;
  const sleeveClause = context.pumpType
    ? `This is a ${vertical ? "VERTICAL" : "HORIZONTAL"} pump.\n` +
      `WETTABLE (media contact - spec metal for media resistance): ${wettable.join(", ")}.\n` +
      `NON-WETTABLE (structural, no media contact - spec metal for strength/cost, do not over-alloy): ${nonWettable.join(", ")}.\n` +
      `ELASTOMER (answer a rubber, not a metal): Stator Rubber. Preferred (not mandatory): ${MOC_AI_ELASTOMERS.join(", ")}.\n`
    : "";
  return (
    `PCP pump. Media: ${context.media}. Pump type: ${pumpType}. Head: ${head}. Capacity: ${capacity}.\n` +
    sleeveClause +
    MOC_REFERENCE +
    `material choice should be optimum \n`+
    `Recommend low-cost reliable MOC (per component), stator elastomer, the shaft seal type AND the seal's own MOC (mechanical seal: body/face/O-ring; gland packing: packing material).\n` +
    `${missingClause}` +
    `summary: concise markdown engineering note. The report already prints the input parameters, the seal recommendation, and the alternatives separately, so DO NOT repeat any of those here (no operating-parameters table, no seal comparison table, no alternatives table). Cover only: a short Key Design Drivers list (bullets) and ONE Component / Material / Why | pipe table | for the wetted metals, stator elastomer and structural parts. Use ## headers and **bold**. Keep it tight. ` +
    `alternatives: markdown with ONE | pipe table | of alternative materials and their trade-offs - do not restate the primary selection or the summary. ` +
    `IMPORTANT: use plain ASCII only. No emoji, no unicode symbols (avoid these: check-mark, cross, warning-triangle, approx-symbol, arrow, bullet-dot). Use "OK" / "X" / "!" / "~" / "->" / "-" instead.` +
    (processData ? `\nOther data:\n${processData}` : "") +
    (context.clientRequirementsFile
      ? `\nClient requirements: SEE THE ATTACHED ${context.clientRequirementsFile.mediaType.startsWith("image/") ? "IMAGE" : "PDF"} in this message. Read it and factor its contents into the recommendation, the same as any other process data - the customer supplied it as part of the enquiry.`
      : "")
  );
}

function line(label: string, value: string | null, unit = ""): string {
  return value && value.trim() !== "" ? `${label}: ${value}${unit}\n` : "";
}

function buildProcessData(context: MocAiContext): string {
  return (
    line("pH", context.ph) +
    line("Temperature", context.temperatureC, " °C") +
    line("Viscosity", context.viscosityCp, " cP") +
    line("SG", context.sg) +
    line("Solids", context.solidPct, "%") +
    line(
      "Particle size",
      context.solidSize,
      context.solidType ? ` mm (${context.solidType})` : " mm",
    )
  );
}

function coerceSuggestions(
  parsed: Partial<Record<string, unknown>>,
  pumpType: string | null,
): MocComponentSuggestions | null {
  // Only the applicable plate is required; the other plate isn't asked for, so
  // it simply comes back empty (get() below returns "" for a missing field).
  if (requiredFieldsFor(pumpType).some((k) => typeof parsed[k] !== "string")) {
    return null;
  }
  const get = (k: keyof MocComponentSuggestions) => {
    const v = parsed[k];
    return typeof v === "string" ? v.trim() : "";
  };
  const out: MocComponentSuggestions = {
    bearingHousing: get("bearingHousing"),
    basePlate: get("basePlate"),
    mountingPlate: get("mountingPlate"),
    tieRod: get("tieRod"),
    nutBolt: get("nutBolt"),
    pumpHousing: get("pumpHousing"),
    rotor: get("rotor"),
    shaft: get("shaft"),
    statorRubber: get("statorRubber"),
    statorSleeve: get("statorSleeve"),
    sealRecommendation: get("sealRecommendation"),
    sealMoc: get("sealMoc"),
    sealRationale: get("sealRationale"),
    summary: get("summary"),
    alternatives: get("alternatives"),
  };
  // Returned as answered — the structural/fastener preference is guidance in
  // the prompt, not an override applied here.
  return out;
}

// Assembles the `content` for the user message. When a client-requirements
// file is attached, it's sent as an image or document content block alongside
// the prompt text - the Anthropic messages API supports both natively for the
// image MIME types (png/jpeg/gif/webp) and PDFs. A missing/unattached file
// falls through to the classic single-string form so the request shape is
// unchanged for the common case.
function buildUserContent(context: MocAiContext, prompt: string):
  | string
  | Array<
      | { type: "text"; text: string }
      | {
          type: "image";
          source: {
            type: "base64";
            media_type: "image/png" | "image/jpeg" | "image/gif" | "image/webp";
            data: string;
          };
        }
      | {
          type: "document";
          source: { type: "base64"; media_type: "application/pdf"; data: string };
        }
    > {
  const file = context.clientRequirementsFile;
  if (!file) return prompt;
  if (file.mediaType.startsWith("image/")) {
    // The list is the exact set Claude's API accepts - the API route already
    // validates the same set on upload, so the cast here is safe.
    return [
      {
        type: "image",
        source: {
          type: "base64",
          media_type: file.mediaType as
            | "image/png"
            | "image/jpeg"
            | "image/gif"
            | "image/webp",
          data: file.base64,
        },
      },
      { type: "text", text: prompt },
    ];
  }
  return [
    {
      type: "document",
      source: { type: "base64", media_type: "application/pdf", data: file.base64 },
    },
    { type: "text", text: prompt },
  ];
}

// --- Anthropic provider (Claude Haiku 4.5) ------------------------------

const ANTHROPIC_MODEL = "claude-haiku-4-5-20251001";
const MOC_TOOL_NAME = "moc_recommendation";

async function getMocAiSuggestionAnthropic(
  context: MocAiContext,
): Promise<MocComponentSuggestions | null> {
  const apiKey = (process.env.ANTHROPIC_API_KEY ?? "").trim();
  if (!apiKey || apiKey.startsWith("REPLACE_")) {
    return null;
  }

  let Anthropic: typeof import("@anthropic-ai/sdk").default;
  try {
    Anthropic = (await import("@anthropic-ai/sdk")).default;
  } catch {
    console.warn("@anthropic-ai/sdk not installed; skipping Anthropic MOC suggestion");
    return null;
  }

  const prompt = buildPrompt(context, buildProcessData(context));

  try {
    const client = new Anthropic({ apiKey });
    const response = await client.messages.create({
      model: ANTHROPIC_MODEL,
      max_tokens: 3500,
      tools: [
        {
          name: MOC_TOOL_NAME,
          description:
            "Records the per-component MOC/elastomer/seal recommendation for a progressive cavity pump.",
          input_schema: {
            type: "object",
            properties: schemaPropertiesFor(context.pumpType),
            required: requiredFieldsFor(context.pumpType),
          },
        },
      ],
      // Force the single tool call rather than letting Claude reply in free
      // text — this is Claude's equivalent of Gemini's responseSchema: the
      // SDK hands back already-parsed JSON in the tool_use block, so there's
      // no free-text JSON to fish out of a chat-style reply.
      tool_choice: { type: "tool", name: MOC_TOOL_NAME },
      messages: [{ role: "user", content: buildUserContent(context, prompt) }],
    });

    if (response.stop_reason === "refusal") {
      console.warn("Anthropic MOC-suggestion request was refused");
      return null;
    }

    const toolUse = response.content.find((b) => b.type === "tool_use");
    if (!toolUse || toolUse.type !== "tool_use") return null;

    return coerceSuggestions(toolUse.input as Partial<Record<string, unknown>>, context.pumpType);
  } catch (err) {
    console.error("Anthropic MOC-suggestion request failed:", err instanceof Error ? err.message : err);
    return null;
  }
}

// --- Dispatch ------------------------------------------------------------

/** Whether the provider has a usable API key configured. Lets the API route
 * report "not configured" (missing/placeholder key) distinctly from "request
 * failed" (key present but the upstream call errored or was blocked), instead
 * of collapsing both into one misleading "not configured" message. The
 * `provider` arg is kept for signature stability though Anthropic is the only
 * option now. */
export function isMocAiProviderConfigured(_provider: MocAiProvider): boolean {
  const key = (process.env.ANTHROPIC_API_KEY ?? "").trim();
  return key !== "" && !key.startsWith("REPLACE_");
}

export async function getMocAiSuggestion(
  context: MocAiContext,
  _provider: MocAiProvider = "anthropic",
): Promise<MocComponentSuggestions | null> {
  return getMocAiSuggestionAnthropic(context);
}
